# Generated by Django 3.2.4 on 2021-06-22 04:46

import django.core.validators
from django.db import migrations, models
import skills.models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skills_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.FileField(upload_to=skills.models.upload_to, validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
