# Generated by Django 3.2.4 on 2021-06-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('intro', models.CharField(max_length=250)),
                ('article', models.CharField(max_length=15000)),
                ('create_Add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
