# Generated by Django 3.2.4 on 2021-07-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210630_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
