# Generated by Django 3.2.4 on 2021-06-24 08:46

import blog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.FileField(upload_to=blog.models.upload_to, validators=[django.core.validators.FileExtensionValidator(['svg'])])),
                ('day_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ManyToManyField(to='blog.Categories')),
            ],
        ),
    ]
